name: My Components Testing

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        # Or run `node --version` in the GitHub Actions runner to see the current Node.js version
        # Or run `nvm --version` in the GitHub Actions runner to see the current Node.js version
        # Or run `nvm ls` in the GitHub Actions runner to see the list of Node.js versions
        # Or run `nvm install 16.x` in the GitHub Actions runner to install the Node.js version
        # Or run `nvm use 16.x` in the GitHub Actions runner to set the Node.js version
        # Or run `nvm alias default 16.x` in the GitHub Actions runner to set the Node.js version as the default version
        # Or run `nvm install 16.x && nvm use 16.x` in the GitHub Actions runner to install and set the Node.js version  
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v2
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Run Jest Tests
      run: |
        npm ci
        npm run build --if-present
        npm test
