name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: write
jobs:
  # Build application aritfacts to be deployed
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] 
    steps:
      - name: Checkout Repository 🛎️
        uses: actions/checkout@v4

      - name: Set up Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: 'yarn'

      - name: Install Dependencies
        run: | 
          yarn  pre-ci
          yarn ci    

      - name: Build React App 🔧 # Create production build
        run: yarn build

      - name: Uploading Built Artifacts 🔺 # The project is then uploaded as an artifact named 'site'.
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build

      - run: |
          pwd
          ls -la
          echo "Listing Built Artifacts"
          ls -la build
  # Perform Unit Testing        
  unit-testing:
    name: Unit Testing
    concurrency: ci-${{ github.ref }}
    needs: build  # This job depends on the successful completion of the 'build' job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: 'yarn'
      
      - name: Install Dependencies
        run: | 
          yarn  pre-ci
          yarn ci      

      - name: Run Jest Tests (Unit Tests)
        run: yarn test
  # Deploy application artifacts to GitHub Pages      
  deploy:
    name: Deploy to GitHub Pages
    concurrency: ci-${{ github.ref }}
    needs: ["build", "unit-testing"]  # This job depends on the successful completion of the 'build' and 'unit-testing' jobs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] 
    steps:
      - name: Checkout Repository 🛎️
        uses: actions/checkout@v4

      - run: |
          mkdir build
        
      - name: Downloading Built artifacts 🔻 # The built project is downloaded into the 'site' folder.        
        uses: actions/download-artifact@v4
        with:
          path: build
          name: build-artifacts                
          
      - name: Deploy Built Files 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: true
          folder: build

      - run: |
          pwd
          ls -la
          ls -la build
  # Perform E2E Testing
  e2e-test:
    name: E2E Tests
    needs: ["build", "deploy"]  # This job depends on the successful completion of the 'build' and 'deploy' jobs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]     
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: 'yarn'
      
      - name: Install Dependencies
        run: | 
          yarn  pre-ci
          yarn ci

      - name: Install ChromeDriver
        run: |        
          # Install ChromeDriver
          CHROME_VERSION=$(google-chrome --version)
          CHROME_DRIVER_VERSION=$(echo "$CHROME_VERSION" | awk '{print $3}')
          
          wget https://storage.googleapis.com/chrome-for-testing-public/$CHROME_DRIVER_VERSION/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip -d /usr/local/bin
          chmod +x /usr/local/bin/chromedriver-linux64/chromedriver

          # Validate versions
          echo "Chrome versions"
          google-chrome --version
          echo "Listing chrome files"
          ls -l /usr/bin/ | grep "google-chrome"
          echo " *********** "
          ls -l /usr/bin/google-chrome
          echo "Chromedriver versions"
          chromedriver --version
        if: runner.os == 'Linux'      

      - name: Run Selenium e2E Tests (if using Selenium)
        run: yarn prod:test:e2e
