name: Continous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v2
      with:
        node-version: ${{matrix.node-version}}
        cache: 'yarn'

    - name: Install Dependencies
      run: | 
        yarn  pre-ci
        yarn ci    

    - name: Build React App
      run: yarn build

    - name: Upload build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-folder
        path: build

    - shell: bash
      run: |
        pwd
        ls -la

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] 
    needs: build  # This job depends on the successful completion of the 'build' job
    steps:
      - name: Download Build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-folder

      - shell: bash
        run: |
          pwd
          ls -la /home/runner/work/my-react-app-with-ts/my-react-app-with-ts
          
      - name: Deploy Built Files 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build

  # Assuming you don't need a separate build step before testing (modify if needed)
  test:
    name: Run Unit and E2E Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] 
    needs: build  # This job depends on the successful completion of the 'build' job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: 'yarn'
      
      - name: Install Dependencies
        run: | 
          yarn  pre-ci
          yarn ci

      - name: Install Chrome and ChromeDriver
        run: |        
          # Install ChromeDriver
          CHROME_VERSION=$(google-chrome --version)
          CHROME_DRIVER_VERSION=$(echo "$CHROME_VERSION" | awk '{print $3}')
          # echo "CHROME_VERSION: $CHROME_VERSION"
          # echo "CHROME_DRIVER_VERSION $CHROME_DRIVER_VERSION"
          
          wget https://storage.googleapis.com/chrome-for-testing-public/$CHROME_DRIVER_VERSION/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip -d /usr/local/bin
          chmod +x /usr/local/bin/chromedriver-linux64/chromedriver

          # Validate versions
          echo "Chrome versions"
          google-chrome --version
          echo "Listing chrome files"
          ls -l /usr/bin/ | grep "google-chrome"
          echo " *********** "
          ls -l /usr/bin/google-chrome
          echo "Chromedriver versions"
          chromedriver --version
        if: runner.os == 'Linux'

      - name: Run Jest Tests (Unit Tests)
        run: yarn test

      - name: Run Selenium e2E Tests (if using Selenium)
        run: yarn test:e2e
